# Generated by Django 3.0.2 on 2020-02-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200107_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-score'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project_default.png', upload_to='project_images'),
        ),
    ]
