# Generated by Django 3.0.2 on 2020-02-20 21:36

from django.db import migrations, models
import django.db.models.deletion
import workshops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='category.Category')),
            ],
            options={
                'verbose_name_plural': 'workshops',
            },
        ),
        migrations.CreateModel(
            name='WorkshopImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=workshops.models.get_image_filename, verbose_name='Image')),
                ('workshop', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.Workshop')),
            ],
        ),
    ]
