# Generated by Django 3.0.2 on 2020-02-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkshopImages',
            new_name='WorkshopImage',
        ),
    ]
