# Generated by Django 3.0.2 on 2020-02-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20200220_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='public',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
